version: '3'

services: 
  lb:
    image: my-haproxy
    ports: 
      - "8080:8080" 
  nodeapp1:
    image: nodeapp
    environment:
      - APPID=1111
  nodeapp2:
    image: nodeapp
    environment:
      - APPID=2222
  nodeapp3:
    image: nodeapp
    environment:
      - APPID=3333